use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'qdmtwokit_Example' do
  pod 'qdmtwokit', :path => '../'

  target 'qdmtwokit_Tests' do
    inherit! :search_paths

    
  end
end
